server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${blog.datasource.driver-class-name}
    url: jdbc:mysql://${blog.datasource.host}:${blog.datasource.port}/${blog.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${blog.datasource.username}
    password: ${blog.datasource.password}
  data:
    redis:
      host: ${blog.redis.host}
      port: ${blog.redis.port}
      password: ${blog.redis.password}
      database: ${blog.redis.database}

mybatis:
  mapper-locations: classpath:com/sau/mapper/*.xml
  type-aliases-package: com.sau.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sau:
        mapper: debug
        service: info
        controller: info
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: ${blog.aliyun.oss.endpoint}
    bucketName: ${blog.aliyun.oss.bucket-name}
    region: ${blog.aliyun.oss.region}
  captcha:
    endpoint: ${blog.aliyun.captcha.endpoint}
    region: ${blog.aliyun.captcha.region}
    scene-id: ${blog.aliyun.captcha.scene-id}
  email:
    endpoint: ${blog.aliyun.email.endpoint}
    account-name: ${blog.aliyun.email.account-name}
    from-alias: ${blog.aliyun.email.from-alias}
