spring:
  application:
    name: blog-project

  # 数据库的链接信息
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1
      jedis:
        pool:
          max-active: 8
          max-wait: 1ms
          max-idle: 4
          min-idle: 0


#Mybatis的相关配置
mybatis:
  configuration:
    #驼峰命名映射
    map-underscore-to-camel-case: true
    #控制台日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云OSS对象存储服务
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-ai-sau
    region: cn-beijing
  captcha:
    endpoint: captcha.cn-shanghai.aliyuncs.com
    region: cn-shanghai
    scene-id: 1h222nka
  email:
    endpoint: dm.aliyuncs.com
    account-name: backend@mail.iiisau.online  # 你的发件人账号
    from-alias: 个人博客                        # 发件人显示名称

